测试的标志
代表意义
1. 关于某个档名的『类型』侦测(存在与否),如 test -e filename
-e 该『档名』是否存在?(常用)
-f 该『档名』是否为档案(file)?(常用)
-d 该『文件名』是否为目录(directory)?(常用)
-b 该『文件名』是否为一个 block device 装置?
-c 该『文件名』是否为一个 character device 装置?
-S 该『档名』是否为一个 Socket 档案?
-p 该『档名』是否为一个 FIFO (pipe) 档案?
-L 该『档名』是否为一个连结档?

. 关于档案的权限侦测,如 test -r filename
-r 侦测该文件名是否具有可读的属性?
-w 侦测该档名是否具有可写的属性?
-x 侦测该档名是否具有可执行的属性?
-u 侦测该文件名是否具有SUID的属性?
-g 侦测该文件名是否具有SGID的属性?
-k 侦测该文件名是否具有Sticky bit的属性?
-s 侦测该档名是否为非空白档案?

两个档案之间的比较,如: test file1 -nt file2
-nt (newer than)判断 file1 是否比 file2 新
-ot (older than)判断 file1 是否比 file2 旧
-ef
判断 file2 与 file2 是否为同一档案,可用在判断 hard link 的
判定上。 主要意义在判定,两个档案是否均指向同一个 inode 哩!

关于两个整数之间的判定,例如 test n1 -eq n2
-eq 两数值相等 (equal)
-ne 两数值不等 (not equal)
-gt n1 大于 n2 (greater than)
-lt n1 小于 n2 (less than)
-ge n1 大于等于 n2 (greater than or equal)
-le n1 小于等于 n2 (less than or equal)


判定字符串的数据
test -z string
test -n string
判定字符串是否为 0 ?若 string 为空字符串,则为 true
判定字符串是否非为 0 ?若 string 为空字符串,则为 false。
注: -n 亦可省略
test str1 = str2 判定 str1 是否等于 str2 ,若相等,则回传 true
test str1 != str2 判定 str1 是否不等于 str2 ,若相等,则回传 false

多重条件判定,例如: test -r filename -a -x filename
-a
-o
!
(and)两状况同时成立!例如 test -r file -a -x file,则 file 同
时具有 r 与 x 权限时,才回传 true。
(or)两状况任何一个成立!例如 test -r file -o -x file,则 file
具有 r 或 x 权限时,就可回传 true。
反相状态,如 test ! -x file ,当 file 不具有 x 时,回传 true
